name: wieisdemol
version: '${version}'
main: nl.mxndarijn.wieisdemol.WieIsDeMol
api-version: 1.19
depend: [ ProtocolLib, TTA ]
commands:
  test:
    Description: Test command for development
    usage: /test
  maps:
    description: maps
    usage: /maps
  presets:
    description: presets
    usage: /presets
  items:
    description: Items
    usage: /items
  skulls:
    description: Custom heads
    usage: /skulls
    aliases:
      - skulls
      - skull
      - head
      - heads
      - heads-database
  spawn:
    description: Spawn
    usage: /spawn
  vanish:
    description: Vanish
    usage: /vanish
    aliases:
      - vanish
      - v
      - laatmenuonzichtbaarzijn
  ms:
    description: Message Speler
    usage: /ms [Speler] [Bericht]
    aliases:
      - ms
      - messagespeler
      - messageplayer