name: WieIsDeMol
version: '${version}'
main: nl.mxndarijn.wieisdemol.WieIsDeMol
commands:
  test:
    Description: Test command for development
    usage: /test
  maps:
    description: maps
    usage: /maps
